name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - anycode-go
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishExtension
    displayName: 🚀 Publish Extension
    type: boolean
    default: false

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    buildSteps:
      - script: cd anycode-go && npm install
        displayName: Install dependencies

      - script: cd anycode && npm install
        displayName: Install dependencies (anycode)

      - script: cd anycode-go && npm run test
        displayName: Run Test Fixtures

    ghCreateTag: true
    ghTagPrefix: anycode-go.v

    publishExtension: ${{ parameters.publishExtension }}

    tsa:
      enabled: true
      options:
        codebaseName: 'devdiv_$(Build.Repository.Name)'
        serviceTreeID: 'c4cd3983-4977-4bcd-931f-a9822d2e950c'
        instanceUrl: 'https://devdiv.visualstudio.com/defaultcollection'
        projectName: 'DevDiv'
        areaPath: "DevDiv\\VS Code (compliance tracking only)\\Visual Studio Code Language Extensions"
        notificationAliases:
          - 'stbatt@microsoft.com'
          - 'lszomoru@microsoft.com'
          - 'jrieken@microsoft.com'

    cgSourceScanPath: $(Build.SourcesDirectory)/anycode-go
    workingDirectory: $(Build.SourcesDirectory)/anycode-go
