name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - anycode-go
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishExtension
    displayName: 🚀 Publish Extension
    type: boolean
    default: false

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    buildSteps:
      - script: cd anycode-go && npm install
        displayName: Install dependencies

      - script: cd anycode && npm install
        displayName: Install dependencies (anycode)

      - script: cd anycode-go && npm run test
        displayName: Run Test Fixtures

    ghCreateTag: true
    ghTagPrefix: anycode-go.v

    publishExtension: ${{ parameters.publishExtension }}

    tsa:
      configFile: $(Build.SourcesDirectory)/tsaoptions.json
      enabled: true

    cgSourceScanPath: $(Build.SourcesDirectory)/anycode-go
    workingDirectory: $(Build.SourcesDirectory)/anycode-go
