name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - anycode-typescript
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishExtension
    displayName: 🚀 Publish Extension
    type: boolean
    default: false

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    buildSteps:
      - script: |
          export npm_config_build_from_source=true
          cd anycode-typescript && npm install
        displayName: Install dependencies

      - script: cd anycode && npm install
        displayName: Install dependencies (anycode)

      - script: cd anycode-typescript && npm run test
        displayName: Run Test Fixtures

    ghCreateTag: true
    ghTagPrefix: anycode-typescript.v

    publishExtension: ${{ parameters.publishExtension }}

    tsa:
      config:
        areaPath: 'Visual Studio Code Language Extensions'
        serviceTreeID: 'c4cd3983-4977-4bcd-931f-a9822d2e950c'
      enabled: true

    cgSourceScanPath: $(Build.SourcesDirectory)/anycode-typescript
    workingDirectory: $(Build.SourcesDirectory)/anycode-typescript
