name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      ANYCODE_TEST_TIMEOUT_MS: '60000'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install anycode dependencies and compile
        run: npm install
        working-directory: anycode

      - name: Lint
        run: npm run lint
        working-directory: anycode

      - name: Test server
        run: npm run test-server
        working-directory: anycode

      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps
        working-directory: anycode/server

      - name: Test anycode-c-sharp
        run: npm install && npm test
        working-directory: anycode-c-sharp

      - name: Test anycode-cpp
        run: npm install && npm test
        working-directory: anycode-cpp

      - name: Test anycode-go
        run: npm install && npm test
        working-directory: anycode-go

      - name: Test anycode-java
        run: npm install && npm test
        working-directory: anycode-java

      - name: Test anycode-kotlin
        run: npm install && npm test
        working-directory: anycode-kotlin

      - name: Test anycode-php
        run: npm install && npm test
        working-directory: anycode-php

      - name: Test anycode-python
        run: npm install && npm test
        working-directory: anycode-python

      - name: Test anycode-rust
        run: npm install && npm test
        working-directory: anycode-rust

      - name: Test anycode-typescript
        run: npm install && npm test
        working-directory: anycode-typescript
